// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReviewLoom.Infrastructure.Data;

#nullable disable

namespace ReviewLoom.Infrastructure.Migrations
{
    [DbContext(typeof(ReviewLoomDbContext))]
    [Migration("20260507033932_AddCampaignStatus")]
    partial class AddCampaignStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReviewLoom.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GoogleReviewUrl")
                        .HasColumnType("text")
                        .HasColumnName("google_review_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("ThankYouMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("thank_you_message")
                        .HasDefaultValueSql("'Thank you for your review!'::text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("campaigns_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Slug" }, "campaigns_slug_key")
                        .IsUnique();

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.CampaignSettings", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<bool>("CollectContact")
                        .HasColumnType("boolean")
                        .HasColumnName("collect_contact");

                    b.Property<string>("CtaLabel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Submit Feedback")
                        .HasColumnName("cta_label");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("How was your experience?")
                        .HasColumnName("heading");

                    b.Property<string>("IncentiveCoupon")
                        .HasColumnType("text")
                        .HasColumnName("incentive_coupon");

                    b.Property<bool>("IncentiveEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("incentive_enabled");

                    b.Property<int>("RoutingThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("routing_threshold");

                    b.Property<string>("ThankYouMessage")
                        .HasColumnType("text")
                        .HasColumnName("thank_you_message");

                    b.HasKey("CampaignId")
                        .HasName("campaign_settings_pkey");

                    b.ToTable("campaign_settings", (string)null);
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.CampaignStandeeConfig", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CtaText")
                        .HasColumnType("text")
                        .HasColumnName("cta_text");

                    b.Property<bool>("ShowLogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_logo");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("minimal_white")
                        .HasColumnName("template_id");

                    b.HasKey("CampaignId")
                        .HasName("campaign_standee_configs_pkey");

                    b.ToTable("campaign_standee_configs", (string)null);
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.CampaignStyle", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("BackgroundGradient")
                        .HasColumnType("text")
                        .HasColumnName("background_gradient");

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("text")
                        .HasColumnName("background_image");

                    b.Property<string>("BackgroundStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("none")
                        .HasColumnName("background_style");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Manrope")
                        .HasColumnName("font_family");

                    b.Property<string>("LogoStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("soft")
                        .HasColumnName("logo_style");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("#0037b0")
                        .HasColumnName("primary_color");

                    b.Property<string>("QrDotColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("#000000")
                        .HasColumnName("qr_dot_color");

                    b.Property<string>("QrFrame")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("none")
                        .HasColumnName("qr_frame");

                    b.Property<string>("RatingIconType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("stars")
                        .HasColumnName("rating_icon_type");

                    b.HasKey("CampaignId")
                        .HasName("campaign_styles_pkey");

                    b.ToTable("campaign_styles", (string)null);
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("FeedbackEmail")
                        .HasColumnType("text")
                        .HasColumnName("feedback_email");

                    b.Property<string>("FeedbackMessage")
                        .HasColumnType("text")
                        .HasColumnName("feedback_message");

                    b.Property<string>("FeedbackName")
                        .HasColumnType("text")
                        .HasColumnName("feedback_name");

                    b.Property<DateTime?>("ScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("scans_pkey");

                    b.HasIndex("CampaignId");

                    b.ToTable("scans", (string)null);
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_provider");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_id");

                    b.Property<string>("ProviderCustomerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_customer_id");

                    b.Property<string>("ProviderSubscriptionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_subscription_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("subscriptions_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<string>("ClerkId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clerk_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "ClerkId" }, "users_clerk_id_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("ReviewLoom.Domain.Entities.User", "User")
                        .WithMany("Campaigns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("campaigns_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.CampaignSettings", b =>
                {
                    b.HasOne("ReviewLoom.Domain.Entities.Campaign", "Campaign")
                        .WithOne("Settings")
                        .HasForeignKey("ReviewLoom.Domain.Entities.CampaignSettings", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.CampaignStandeeConfig", b =>
                {
                    b.HasOne("ReviewLoom.Domain.Entities.Campaign", "Campaign")
                        .WithOne("StandeeConfig")
                        .HasForeignKey("ReviewLoom.Domain.Entities.CampaignStandeeConfig", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.CampaignStyle", b =>
                {
                    b.HasOne("ReviewLoom.Domain.Entities.Campaign", "Campaign")
                        .WithOne("Style")
                        .HasForeignKey("ReviewLoom.Domain.Entities.CampaignStyle", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.Scan", b =>
                {
                    b.HasOne("ReviewLoom.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Scans")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("scans_campaign_id_fkey");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("ReviewLoom.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("subscriptions_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Scans");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("StandeeConfig");

                    b.Navigation("Style")
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewLoom.Domain.Entities.User", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
